[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xblock-processline"
dynamic = ["version"]
description = "Process Line XBlock is an XBlock which is used to demonstrate how process steps evolves"
readme = "README.rst"
license = {file = "LICENSE.txt"}
requires-python = ">=3.8"
authors = [
    { name = "OpenCraft", email = "help+xblock@opencraft.com" },
]
keywords = [
    "Python",
    "edx",
    "XBlock",
    "openedx",
    "TypeScript",
    "plugin",
    "tsx",
    "jsx",
    "vite",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "edx-i18n-tools",
    "XBlock",
    "xblock-utils",
    "pydantic < 3.0",
]

[project.entry-points."xblock.v1"]
processline = "processline:ProcesslineXBlock"

[project.urls]
Homepage = "https://github.com/open-craft/xblock-processline"

[tool.hatch.version]
path = "processline/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/processline",
]
[tool.hatch.build.targets.wheel]
packages = ["processline"]

[tool.isort]
include_trailing_comma = true
indent = '    '
line_length = 120
multi_line_output = 3
skip=["migrations"]

[tool.ruff]
line-length = 120
target-version = "py38"
extend-exclude = ["processline_venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]
